"""empty message

Revision ID: 1d2a0ae9899c
Revises: ef980ce0f8f7
Create Date: 2022-12-17 15:26:54.408722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d2a0ae9899c'
down_revision = 'ef980ce0f8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=True))
        batch_op.drop_column('duration')

    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_column('availability')

    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('discount')
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
