"""empty message

Revision ID: 24c0c51f9981
Revises: acb8495d0332
Create Date: 2022-12-20 19:11:01.088354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24c0c51f9981'
down_revision = 'acb8495d0332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('voucher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher', mysql.VARCHAR(length=15), nullable=True))

    # ### end Alembic commands ###
