"""empty message

Revision ID: 32ffa881cae6
Revises: dc12f9d2c90e
Create Date: 2022-12-21 16:58:41.022945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ffa881cae6'
down_revision = 'dc12f9d2c90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'instrument', ['client'], ['user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date')
        batch_op.drop_column('model')
        batch_op.drop_column('client')

    # ### end Alembic commands ###
