"""empty message

Revision ID: 57e8faf622dc
Revises: b81b224c6ebb
Create Date: 2022-12-19 20:36:56.396239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57e8faf622dc'
down_revision = 'b81b224c6ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_ibfk_3', type_='foreignkey')
        batch_op.drop_column('renter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renter', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key('order_ibfk_3', 'instrument', ['renter'], ['user'])

    # ### end Alembic commands ###
