"""empty message

Revision ID: 62d86bec772e
Revises: aebe084b6e15
Create Date: 2022-12-20 19:51:46.164728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62d86bec772e'
down_revision = 'aebe084b6e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pay_by', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(None, 'payment', ['pay_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', mysql.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pay_by')
        batch_op.drop_column('pay_id')

    # ### end Alembic commands ###
