"""empty message

Revision ID: 9747c31d97e1
Revises: 17cddf6edcc6
Create Date: 2022-12-14 04:38:25.815233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9747c31d97e1'
down_revision = '17cddf6edcc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_constraint('instrument_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user'], ['username'])
        batch_op.drop_column('username')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('instrument_ibfk_1', 'user', ['username'], ['username'])

    # ### end Alembic commands ###
