"""empty message

Revision ID: b81b224c6ebb
Revises: 1d2a0ae9899c
Create Date: 2022-12-19 20:21:11.764012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81b224c6ebb'
down_revision = '1d2a0ae9899c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renter', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'instrument', ['renter'], ['user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('delivery')
        batch_op.drop_column('renter')

    # ### end Alembic commands ###
