"""empty message

Revision ID: bbfa81904562
Revises: 464167eea629
Create Date: 2022-12-21 17:52:39.516223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfa81904562'
down_revision = '464167eea629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_contact', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('user_address', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('client_contact', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('client_address', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('client_address')
        batch_op.drop_column('client_contact')
        batch_op.drop_column('user_address')
        batch_op.drop_column('user_contact')

    # ### end Alembic commands ###
