"""empty message

Revision ID: c68540ae7037
Revises: 
Create Date: 2022-12-07 16:46:55.087088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68540ae7037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['contact'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dob')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
