"""empty message

Revision ID: caa07ffab522
Revises: 57e8faf622dc
Create Date: 2022-12-20 01:19:16.392203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caa07ffab522'
down_revision = '57e8faf622dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('owner', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.username'], name='cart_ibfk_2'),
    sa.ForeignKeyConstraint(['product'], ['instrument.id'], name='cart_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
