"""empty message

Revision ID: ef980ce0f8f7
Revises: d22c164dbf54
Create Date: 2022-12-16 08:56:39.322982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef980ce0f8f7'
down_revision = 'd22c164dbf54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('validity', sa.Date(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=15), nullable=False))
        batch_op.drop_column('validity')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
